USE [master]
GO

/****** Object:  Database [AlbatrosLab]    Script Date: 25/6/2022 15:17:49 ******/
CREATE DATABASE [AlbatrosLab]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AlbatrosLab', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AlbatrosLab.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AlbatrosLab_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AlbatrosLab_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AlbatrosLab].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AlbatrosLab] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AlbatrosLab] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AlbatrosLab] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AlbatrosLab] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AlbatrosLab] SET ARITHABORT OFF 
GO

ALTER DATABASE [AlbatrosLab] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AlbatrosLab] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AlbatrosLab] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AlbatrosLab] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AlbatrosLab] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AlbatrosLab] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AlbatrosLab] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AlbatrosLab] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AlbatrosLab] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AlbatrosLab] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AlbatrosLab] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AlbatrosLab] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AlbatrosLab] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AlbatrosLab] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AlbatrosLab] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AlbatrosLab] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AlbatrosLab] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AlbatrosLab] SET RECOVERY FULL 
GO

ALTER DATABASE [AlbatrosLab] SET  MULTI_USER 
GO

ALTER DATABASE [AlbatrosLab] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AlbatrosLab] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AlbatrosLab] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AlbatrosLab] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AlbatrosLab] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AlbatrosLab] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AlbatrosLab] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AlbatrosLab] SET  READ_WRITE 
GO


